CREATE TABLE public."Branch" (
    "BranchId" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."Branch" OWNER TO magisterka;

--
-- TOC entry 203 (class 1259 OID 16390)
-- Name: Branch_BranchId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Branch" ALTER COLUMN "BranchId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Branch_BranchId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16447)
-- Name: Commits; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."Commits" (
    "CommitId" integer NOT NULL,
    "Sha" text,
    "Message" text,
    "Date" timestamp without time zone NOT NULL,
    "DeveloperId" integer NOT NULL,
    "RepositoryId" bigint NOT NULL,
    "BranchId" integer
);


ALTER TABLE public."Commits" OWNER TO magisterka;

--
-- TOC entry 213 (class 1259 OID 16445)
-- Name: Commits_CommitId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Commits" ALTER COLUMN "CommitId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Commits_CommitId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 16402)
-- Name: Developers; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."Developers" (
    "DeveloperId" integer NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "FirstName" text,
    "LastName" text
);


ALTER TABLE public."Developers" OWNER TO magisterka;

--
-- TOC entry 205 (class 1259 OID 16400)
-- Name: Developers_DeveloperId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Developers" ALTER COLUMN "DeveloperId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Developers_DeveloperId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16432)
-- Name: FileDetails; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."FileDetails" (
    "FileDetailId" integer NOT NULL,
    "Name" text,
    "Extension" text,
    "FullPath" text,
    "LanguageId" integer
);


ALTER TABLE public."FileDetails" OWNER TO magisterka;

--
-- TOC entry 211 (class 1259 OID 16430)
-- Name: FileDetails_FileDetailId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."FileDetails" ALTER COLUMN "FileDetailId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FileDetails_FileDetailId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16472)
-- Name: Files; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."Files" (
    "FileId" integer NOT NULL,
    "SHA" text,
    "FileDetailId" integer,
    "CommitId" integer NOT NULL,
    "Status" text
);


ALTER TABLE public."Files" OWNER TO magisterka;

--
-- TOC entry 215 (class 1259 OID 16470)
-- Name: Files_FileId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Files" ALTER COLUMN "FileId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Files_FileId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 16412)
-- Name: Languages; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."Languages" (
    "LanguageId" integer NOT NULL,
    "Name" text
);


ALTER TABLE public."Languages" OWNER TO magisterka;

--
-- TOC entry 207 (class 1259 OID 16410)
-- Name: Languages_LanguageId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Languages" ALTER COLUMN "LanguageId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Languages_LanguageId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16492)
-- Name: Metrics; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."Metrics" (
    "MetricId" integer NOT NULL,
    "Complexity" integer,
    "CognitiveComplexity" integer,
    "DuplicatedLines" integer,
    "CodeSmells" integer,
    "NewCodeSmells" integer,
    "CommentLines" integer,
    "CommentLinesDensity" double precision,
    "Ncloc" integer,
    "Statements" integer,
    "BranchCoverage" double precision,
    "LineCoverage" double precision,
    "Date" timestamp without time zone NOT NULL,
    "FileId" integer NOT NULL
);


ALTER TABLE public."Metrics" OWNER TO magisterka;

--
-- TOC entry 217 (class 1259 OID 16490)
-- Name: Metrics_MetricId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Metrics" ALTER COLUMN "MetricId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Metrics_MetricId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16422)
-- Name: Repositories; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."Repositories" (
    "RepositoryId" bigint NOT NULL,
    "Name" text NOT NULL,
    "FullName" text,
    "Url" text,
    "Private" boolean NOT NULL,
    "Key" text
);


ALTER TABLE public."Repositories" OWNER TO magisterka;

--
-- TOC entry 209 (class 1259 OID 16420)
-- Name: Repositories_RepositoryId_seq; Type: SEQUENCE; Schema: public; Owner: magisterka
--

ALTER TABLE public."Repositories" ALTER COLUMN "RepositoryId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Repositories_RepositoryId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 202 (class 1259 OID 16385)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: magisterka
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO magisterka;

--
-- TOC entry 2990 (class 0 OID 16392)
-- Dependencies: 204
-- Data for Name: Branch; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 3000 (class 0 OID 16447)
-- Dependencies: 214
-- Data for Name: Commits; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 2992 (class 0 OID 16402)
-- Dependencies: 206
-- Data for Name: Developers; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 2998 (class 0 OID 16432)
-- Dependencies: 212
-- Data for Name: FileDetails; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 3002 (class 0 OID 16472)
-- Dependencies: 216
-- Data for Name: Files; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 2994 (class 0 OID 16412)
-- Dependencies: 208
-- Data for Name: Languages; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 3004 (class 0 OID 16492)
-- Dependencies: 218
-- Data for Name: Metrics; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 2996 (class 0 OID 16422)
-- Dependencies: 210
-- Data for Name: Repositories; Type: TABLE DATA; Schema: public; Owner: magisterka
--



--
-- TOC entry 2988 (class 0 OID 16385)
-- Dependencies: 202
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: magisterka
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20201112082735_InitialCreate', '3.1.10');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20201124114244_UpdateKeys', '3.1.10');


--
-- TOC entry 3011 (class 0 OID 0)
-- Dependencies: 203
-- Name: Branch_BranchId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Branch_BranchId_seq"', 1, false);


--
-- TOC entry 3012 (class 0 OID 0)
-- Dependencies: 213
-- Name: Commits_CommitId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Commits_CommitId_seq"', 1, false);


--
-- TOC entry 3013 (class 0 OID 0)
-- Dependencies: 205
-- Name: Developers_DeveloperId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Developers_DeveloperId_seq"', 1, false);


--
-- TOC entry 3014 (class 0 OID 0)
-- Dependencies: 211
-- Name: FileDetails_FileDetailId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."FileDetails_FileDetailId_seq"', 1, false);


--
-- TOC entry 3015 (class 0 OID 0)
-- Dependencies: 215
-- Name: Files_FileId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Files_FileId_seq"', 1, false);


--
-- TOC entry 3016 (class 0 OID 0)
-- Dependencies: 207
-- Name: Languages_LanguageId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Languages_LanguageId_seq"', 1, false);


--
-- TOC entry 3017 (class 0 OID 0)
-- Dependencies: 217
-- Name: Metrics_MetricId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Metrics_MetricId_seq"', 1, false);


--
-- TOC entry 3018 (class 0 OID 0)
-- Dependencies: 209
-- Name: Repositories_RepositoryId_seq; Type: SEQUENCE SET; Schema: public; Owner: magisterka
--

SELECT pg_catalog.setval('public."Repositories_RepositoryId_seq"', 1, false);


--
-- TOC entry 2833 (class 2606 OID 16399)
-- Name: Branch PK_Branch; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Branch"
    ADD CONSTRAINT "PK_Branch" PRIMARY KEY ("BranchId");


--
-- TOC entry 2847 (class 2606 OID 16624)
-- Name: Commits PK_Commits; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Commits"
    ADD CONSTRAINT "PK_Commits" PRIMARY KEY ("CommitId");


--
-- TOC entry 2835 (class 2606 OID 16593)
-- Name: Developers PK_Developers; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Developers"
    ADD CONSTRAINT "PK_Developers" PRIMARY KEY ("DeveloperId");


--
-- TOC entry 2842 (class 2606 OID 16577)
-- Name: FileDetails PK_FileDetails; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."FileDetails"
    ADD CONSTRAINT "PK_FileDetails" PRIMARY KEY ("FileDetailId");


--
-- TOC entry 2851 (class 2606 OID 16560)
-- Name: Files PK_Files; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Files"
    ADD CONSTRAINT "PK_Files" PRIMARY KEY ("FileId");


--
-- TOC entry 2837 (class 2606 OID 16419)
-- Name: Languages PK_Languages; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Languages"
    ADD CONSTRAINT "PK_Languages" PRIMARY KEY ("LanguageId");


--
-- TOC entry 2854 (class 2606 OID 16522)
-- Name: Metrics PK_Metrics; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Metrics"
    ADD CONSTRAINT "PK_Metrics" PRIMARY KEY ("MetricId");


--
-- TOC entry 2839 (class 2606 OID 16429)
-- Name: Repositories PK_Repositories; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Repositories"
    ADD CONSTRAINT "PK_Repositories" PRIMARY KEY ("RepositoryId");


--
-- TOC entry 2831 (class 2606 OID 16389)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2843 (class 1259 OID 16502)
-- Name: IX_Commits_BranchId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE INDEX "IX_Commits_BranchId" ON public."Commits" USING btree ("BranchId");


--
-- TOC entry 2844 (class 1259 OID 16606)
-- Name: IX_Commits_DeveloperId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE INDEX "IX_Commits_DeveloperId" ON public."Commits" USING btree ("DeveloperId");


--
-- TOC entry 2845 (class 1259 OID 16504)
-- Name: IX_Commits_RepositoryId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE INDEX "IX_Commits_RepositoryId" ON public."Commits" USING btree ("RepositoryId");


--
-- TOC entry 2840 (class 1259 OID 16505)
-- Name: IX_FileDetails_LanguageId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE INDEX "IX_FileDetails_LanguageId" ON public."FileDetails" USING btree ("LanguageId");


--
-- TOC entry 2848 (class 1259 OID 16543)
-- Name: IX_Files_CommitId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE INDEX "IX_Files_CommitId" ON public."Files" USING btree ("CommitId");


--
-- TOC entry 2849 (class 1259 OID 16528)
-- Name: IX_Files_FileDetailId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE INDEX "IX_Files_FileDetailId" ON public."Files" USING btree ("FileDetailId");


--
-- TOC entry 2852 (class 1259 OID 16509)
-- Name: IX_Metrics_FileId; Type: INDEX; Schema: public; Owner: magisterka
--

CREATE UNIQUE INDEX "IX_Metrics_FileId" ON public."Metrics" USING btree ("FileId");


--
-- TOC entry 2856 (class 2606 OID 16455)
-- Name: Commits FK_Commits_Branch_BranchId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Commits"
    ADD CONSTRAINT "FK_Commits_Branch_BranchId" FOREIGN KEY ("BranchId") REFERENCES public."Branch"("BranchId") ON DELETE RESTRICT;


--
-- TOC entry 2858 (class 2606 OID 16607)
-- Name: Commits FK_Commits_Developers_DeveloperId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Commits"
    ADD CONSTRAINT "FK_Commits_Developers_DeveloperId" FOREIGN KEY ("DeveloperId") REFERENCES public."Developers"("DeveloperId") ON DELETE CASCADE;


--
-- TOC entry 2857 (class 2606 OID 16465)
-- Name: Commits FK_Commits_Repositories_RepositoryId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Commits"
    ADD CONSTRAINT "FK_Commits_Repositories_RepositoryId" FOREIGN KEY ("RepositoryId") REFERENCES public."Repositories"("RepositoryId") ON DELETE CASCADE;


--
-- TOC entry 2855 (class 2606 OID 16440)
-- Name: FileDetails FK_FileDetails_Languages_LanguageId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."FileDetails"
    ADD CONSTRAINT "FK_FileDetails_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES public."Languages"("LanguageId") ON DELETE RESTRICT;


--
-- TOC entry 2860 (class 2606 OID 16625)
-- Name: Files FK_Files_Commits_CommitId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Files"
    ADD CONSTRAINT "FK_Files_Commits_CommitId" FOREIGN KEY ("CommitId") REFERENCES public."Commits"("CommitId") ON DELETE CASCADE;


--
-- TOC entry 2859 (class 2606 OID 16578)
-- Name: Files FK_Files_FileDetails_FileDetailId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Files"
    ADD CONSTRAINT "FK_Files_FileDetails_FileDetailId" FOREIGN KEY ("FileDetailId") REFERENCES public."FileDetails"("FileDetailId") ON DELETE RESTRICT;


--
-- TOC entry 2861 (class 2606 OID 16561)
-- Name: Metrics FK_Metrics_Files_FileId; Type: FK CONSTRAINT; Schema: public; Owner: magisterka
--

ALTER TABLE ONLY public."Metrics"
    ADD CONSTRAINT "FK_Metrics_Files_FileId" FOREIGN KEY ("FileId") REFERENCES public."Files"("FileId") ON DELETE CASCADE;


-- Completed on 2020-12-07 21:43:08

--
-- PostgreSQL database dump complete
--

